apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.INGRESS_NAME | default "ingress-wildcard-host" }}
  labels:
    app: {{ .Values.ingress.APP_NAME | default "helm-calci" }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.INGRESS_CLASS | default "nginx" }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  ingressClassName: {{ .Values.ingress.INGRESS_CLASS | default "nginx" }}
  rules:
    - host: {{ .Values.ingress.HOST_NAME | default "localhost" | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.PATH | default "/" }}
            pathType: {{ .Values.ingress.PATH_TYPE | default "Prefix" }}
            backend:
              service:
                name: {{ .Values.ingress.SERVICE_NAME | default "helm-calculator-service" }}
                port:
                  number: {{ .Values.ingress.SERVICE_PORT | default 80 }}
